{{- if ne .Values.mcpo.config "" }}
apiVersion: v1
kind: Secret
metadata:
  name: mcpo-config
  namespace: {{ .Release.Namespace }}
stringData:
  config.json: |
    {{- .Values.mcpo.config | nindent 4 }}
{{- end }}
